language: node_js
node_js:
  - '10'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  target-branch: master
  script: npm run build
  on:
    branch: develop